### ISSUE TITLE
question: working with a vue frontend and a DRF backend...

### ISSUE THREAD

**Issue by fessacchiotto** [sirrobot01/django-request-viewer#3]
Hello! Thanks for sharing your code. Are there any suggestions to make the app working with a vue frontend and a DRF backend? in case of token or jwt authentications it looks like all the authenticated requests to the backend are intercepted and thus unauthenticated.

**Comment by sunithvs** [comment]
if you don't want the request logging in login you can specify the url which course the error (in my case ' google_login/ ') can be added to WHITELISTED_PATH in settings 

like 
REQUEST_VIEWER = {
    "LIVE_MONITORING": True,
    "WHITELISTED_PATH": [ADMIN_URL, 'login/', 'logout/', 'google_login/']
}
